%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-qt-dotgraph
Version:        2.9.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS qt_dotgraph package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-pydot
Requires:       python%{python3_pkgversion}-pygraphviz
Requires:       ros-kilted-python-qt-binding >= 0.3.0
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
BuildRequires:  ros-kilted-ament-xmllint
%endif

%description
qt_dotgraph provides helpers to work with dot graphs.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Chris Lalancette <clalancette@gmail.com> - 2.9.0-2
- Autogenerated by Bloom

* Fri Dec 20 2024 Chris Lalancette <clalancette@gmail.com> - 2.9.0-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.8.3-1
- Autogenerated by Bloom

* Wed Jul 10 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.8.2-1
- Autogenerated by Bloom

* Tue Jun 25 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.8.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.8.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.7.4-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.7.3-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Dirk Thomas <dthomas@osrfoundation.org> - 2.7.2-2
- Autogenerated by Bloom

